german_terms = [
    "Erythrozyten",
    "Hämoglobin",
    "Hämatokrit",
    "MCH (HbE)",
    "MCV",
    "MCHC",
    "Erythrozytenverteilungsbreite",
    "Leukozyten",
    "Thrombozyten",
    "neutrophile Granulozyten",
    "eosinophile Granulozyten",
    "basophile Granulozyten",
    "Lymphozyten",
    "Monozyten",
    "neutrophile Granulozyten",
    "eosinophile Granulozyten",
    "basophile Granulozyten",
    "Lymphozyten",
    "Monozyten",
    "Glucose venös (μlasma)",
    "Kreatinin",
    "GFR (CKD-Eμl-Formel)",
    "Harnsäure",
    "Cholesterin, Gesamtgrenzwertig",
    "HDL-Cholesterin",
    "LDL-Cholesterin",
    "Triglyceride",
    "GOT (ASAT)",
    "GPT (ALAT)",
    "gamma-GT",
    "TSH, basal",
    "Vitamin D, 25-Hydroxy-",
]

english_translations = [
    "red blood cells",
    "hemoglobin",
    "hematocrit",
    "MCH (mean corpuscular hemoglobin)",
    "MCV (mean corpuscular volume)",
    "MCHC (mean corpuscular hemoglobin concentration)",
    "red blood cell distribution width",
    "leukocytes",
    "μlatelets",
    "neutrophil granulocytes",
    "eosinophil granulocytes",
    "basophil granulocytes",
    "lymphocytes",
    "monocytes",
    "neutrophil granulocytes",
    "eosinophil granulocytes",
    "basophil granulocytes",
    "lymphocytes",
    "monocytes",
    "μlasma glucose",
    "creatinine",
    "GFR (CKD-EPI formula)",
    "uric acid",
    "Cholesterol",
    "HDL-Cholesterol",
    "LDL-Cholesterol",
    "Triglyceride",
    "GOT (ASAT)",
    "GPT (ALAT)",
    "gamma-GT",
    "TSH, basal",
    "Vitamine D, 25-Hydroxy-",
]
medical_units = [
    "Mio./μl",
    "g/dl",
    "%",
    "pg/Ery",
    "fl",
    "g/dl",
    "%",
    "Tsd./μl",
    "Tsd./μl",
    "%",
    "%",
    "%",
    "%",
    "%",
    "Tsd./μl",
    "Tsd./μl",
    "Tsd./μl",
    "Tsd./μl",
    "Tsd./μl",
    "mg/dl",
    "mg/dl",
    "ml/min",
    "mg/dl",
    "mg/dl",
    "mg/dl",
    "mg/dl",
    "mg/dl",
    "U/L",
    "U/L",
    "U/L",
    "mU/L",
    "μg/l",
]

upper_bound = [
    5.77,
    17.5,
    51,
    32.8,
    96.0,
    36.6,
    14.8,
    9.8,
    328,
    75,
    7,
    2,
    47,
    12,
    6.2,
    0.44,
    0.080,
    3.200,
    0.87,
    100,
    1.2,
    60,
    7.2,
    200,
    40,
    116,
    150,
    50,
    50,
    60,
    4.0,
    30,
]

lower_bound = [
    4.54,
    13.5,
    40,
    27.6,
    80.0,
    32.8,
    -1,
    3.9,
    146,
    40,
    -1,
    -1,
    17,
    4,
    1.800,
    0.030,
    0.010,
    1.100,
    0.260,
    65,
    -1,
    -2,
    -1,
    -1,
    -2,
    -1,
    -1,
    -1,
    -1,
    -1,
    0.30,
    -2,
]
medical_dict = {}

medical_dict = "{"
for eng, germ, unit, lower_b, upper_b in zip(
    english_translations, german_terms, medical_units, lower_bound, upper_bound
):
    one_json_obj = f""" "{eng}": {"{"}
    "german": {germ},
    "unit": {unit},
    "lower_bound": {lower_b},
    "upper_bound": {upper_b}
    {"}"}
    """
    medical_dict += one_json_obj + ",\n"

medical_dict += "}"

open("final_dict", "w").write(medical_dict)
